server_name: defta-covers
port: 4222
http_port: 8222

authorization {
  user: $NATS_USER
  password: $NATS_PASSWORD
  timeout: 2
}

jetstream {
  store_dir: /data/jetstream
  max_memory_store: 64MB
  max_file_store: 2GB
}

write_deadline: "10s"
max_payload: 8MB
