package repositories

import("context";"database/sql";"errors";"fmt")
var ErrCoverImportJobNotFound=errors.New("cover import job not found")
var ErrCoverImportJobState=errors.New("cover import job is not pending moderation")
type CoverImportModerationJob struct{ID,LibraryID,ActorUserID,SourceObjectKey,SourceContentType string;SourceSize int64}
type PendingCoverImportOutboxEvent struct{EventID,Payload string}
func(r *CoverImportRepository)PendingModerationOutbox(ctx context.Context,now string,limit int)([]PendingCoverImportOutboxEvent,error){if limit<1||limit>100{return nil,ErrInvalidCoverImport};rows,err:=r.db.QueryContext(ctx,`SELECT event_id,payload FROM cover_import_outbox WHERE event_type='cover.imports.moderate.v1' AND published_at IS NULL AND available_at<=? ORDER BY created_at,event_id LIMIT ?`,now,limit);if err!=nil{return nil,fmt.Errorf("list cover import outbox: %w",err)};defer rows.Close();events:=[]PendingCoverImportOutboxEvent{};for rows.Next(){var event PendingCoverImportOutboxEvent;if err=rows.Scan(&event.EventID,&event.Payload);err!=nil{return nil,err};events=append(events,event)};return events,rows.Err()}
func(r *CoverImportRepository)MarkModerationOutboxPublished(ctx context.Context,eventID,now string)error{result,err:=r.db.ExecContext(ctx,`UPDATE cover_import_outbox SET published_at=?,last_error=NULL WHERE event_id=? AND event_type='cover.imports.moderate.v1' AND published_at IS NULL`,now,eventID);if err!=nil{return err};rows,_:=result.RowsAffected();if rows!=1{return ErrCoverImportJobNotFound};return nil}
func(r *CoverImportRepository)RecordModerationOutboxFailure(ctx context.Context,eventID,message,now string)error{if message==""{message="publish_failed"};_,err:=r.db.ExecContext(ctx,`UPDATE cover_import_outbox SET attempts=attempts+1,last_error=?,available_at=? WHERE event_id=? AND event_type='cover.imports.moderate.v1' AND published_at IS NULL`,message,now,eventID);return err}
func(r *CoverImportRepository)ClaimForModeration(ctx context.Context,jobID,now string)(CoverImportModerationJob,error){tx,err:=r.db.BeginTx(ctx,nil);if err!=nil{return CoverImportModerationJob{},fmt.Errorf("begin claim cover import: %w",err)};defer tx.Rollback();var job CoverImportModerationJob;err=tx.QueryRowContext(ctx,`SELECT id,library_id,actor_user_id,source_object_key,source_content_type,source_size FROM cover_import_jobs WHERE id=? AND status='PENDING_SCAN'`,jobID).Scan(&job.ID,&job.LibraryID,&job.ActorUserID,&job.SourceObjectKey,&job.SourceContentType,&job.SourceSize);if errors.Is(err,sql.ErrNoRows){return job,ErrCoverImportJobNotFound};if err!=nil{return job,fmt.Errorf("read cover import job: %w",err)};result,err:=tx.ExecContext(ctx,`UPDATE cover_import_jobs SET status='NSFW_SCANNING',updated_at=? WHERE id=? AND status='PENDING_SCAN'`,now,jobID);if err!=nil{return job,fmt.Errorf("claim cover import job: %w",err)};rows,_:=result.RowsAffected();if rows!=1{return job,ErrCoverImportJobState};if err=tx.Commit();err!=nil{return job,fmt.Errorf("commit claim cover import: %w",err)};return job,nil}
func(r *CoverImportRepository)CompleteModeration(ctx context.Context,job CoverImportModerationJob,class,modelVersion,eventID,auditID,now string)error{if job.ID==""||auditID==""||modelVersion==""||(class!="SAFE"&&class!="REVIEW"&&class!="UNSAFE")||(class=="SAFE"&&eventID==""){return ErrInvalidCoverImport};status,code:="QUARANTINED","MODEL_REVIEW";if class=="SAFE"{status,code="OCR_PENDING","MODEL_SAFE"};if class=="UNSAFE"{status,code="REJECTED","MODEL_UNSAFE"};tx,err:=r.db.BeginTx(ctx,nil);if err!=nil{return fmt.Errorf("begin cover import moderation: %w",err)};defer tx.Rollback();result,err:=tx.ExecContext(ctx,`UPDATE cover_import_jobs SET status=?,nsfw_decision=?,nsfw_policy_version=?,decision_code=?,updated_at=?,terminal_at=CASE WHEN ? IN ('QUARANTINED','REJECTED') THEN ? ELSE NULL END WHERE id=? AND status='NSFW_SCANNING'`,status,class,modelVersion,code,now,status,now,job.ID);if err!=nil{return fmt.Errorf("update cover import moderation: %w",err)};rows,_:=result.RowsAffected();if rows!=1{return ErrCoverImportJobState};if class=="SAFE"{payload:=fmt.Sprintf(`{"schemaVersion":1,"eventId":%q,"jobId":%q,"libraryId":%q,"attempt":1}`,eventID,job.ID,job.LibraryID);if _,err=tx.ExecContext(ctx,`INSERT INTO cover_import_outbox(event_id,job_id,library_id,event_type,schema_version,payload,attempts,available_at,created_at) VALUES(?,?,?,'cover.imports.ocr.v1',1,?,0,?,?)`,eventID,job.ID,job.LibraryID,payload,now,now);err!=nil{return fmt.Errorf("queue cover import OCR: %w",err)}};if _,err=tx.ExecContext(ctx,`INSERT INTO audit_logs(id,actor_user_id,action,resource_type,resource_id,new_values,success,created_at) VALUES(?,?, 'DECIDE_COVER_IMPORT_MODERATION','COVER_IMPORT_JOB',?,?,1,?)`,auditID,job.ActorUserID,job.ID,fmt.Sprintf(`{"class":%q,"decisionCode":%q,"modelVersion":%q}`,class,code,modelVersion),now);err!=nil{return fmt.Errorf("audit cover import moderation: %w",err)};return tx.Commit()}
func(r *CoverImportRepository)FailModeration(ctx context.Context,jobID,code,auditID,now string)error{tx,err:=r.db.BeginTx(ctx,nil);if err!=nil{return fmt.Errorf("begin failed cover import moderation: %w",err)};defer tx.Rollback();var actor string;err=tx.QueryRowContext(ctx,`SELECT actor_user_id FROM cover_import_jobs WHERE id=? AND status='NSFW_SCANNING'`,jobID).Scan(&actor);if errors.Is(err,sql.ErrNoRows){return ErrCoverImportJobState};if err!=nil{return err};result,err:=tx.ExecContext(ctx,`UPDATE cover_import_jobs SET status='FAILED',failure_code=?,updated_at=?,terminal_at=? WHERE id=? AND status='NSFW_SCANNING'`,code,now,now,jobID);if err!=nil{return err};rows,_:=result.RowsAffected();if rows!=1{return ErrCoverImportJobState};if _,err=tx.ExecContext(ctx,`INSERT INTO audit_logs(id,actor_user_id,action,resource_type,resource_id,new_values,success,created_at) VALUES(?,?, 'DECIDE_COVER_IMPORT_MODERATION','COVER_IMPORT_JOB',?,?,0,?)`,auditID,actor,jobID,fmt.Sprintf(`{"failureCode":%q}`,code),now);err!=nil{return err};return tx.Commit()}
