package handlers

import (
	"defta-librairie/internal/auth"
	"defta-librairie/internal/models"
	"defta-librairie/internal/repositories"
	"defta-librairie/internal/services"
	"errors"
	"net/http"
)

type ReturnSettlementHandler struct{service *services.ReturnSettlementService}
func NewReturnSettlementHandler(service *services.ReturnSettlementService)*ReturnSettlementHandler{return &ReturnSettlementHandler{service:service}}
func(h *ReturnSettlementHandler)List(w http.ResponseWriter,r *http.Request){offset,limit:=normalizeAPIPagination(r.URL.Query().Get("offset"),r.URL.Query().Get("limit"),30);claims,_:=auth.ClaimsFromContext(r.Context());values,total,err:=h.service.List(r.Context(),claims,r.PathValue("id"),models.ReturnSettlementFilter{Method:models.ReturnSettlementMethod(r.URL.Query().Get("method")),Status:models.ReturnSettlementStatus(r.URL.Query().Get("status"))},offset,limit);if err!=nil{writeReturnSettlementError(w,err);return};writeAuthJSON(w,http.StatusOK,map[string]interface{}{"results":values,"total":total,"offset":offset,"limit":limit})}
func(h *ReturnSettlementHandler)Balance(w http.ResponseWriter,r *http.Request){claims,_:=auth.ClaimsFromContext(r.Context());value,err:=h.service.Balance(r.Context(),claims,r.PathValue("id"));if err!=nil{writeReturnSettlementError(w,err);return};writeAuthJSON(w,http.StatusOK,value)}
func(h *ReturnSettlementHandler)Create(w http.ResponseWriter,r *http.Request){var input models.ReturnSettlementInput;if decodeOwnerJSON(w,r,&input)!=nil{writeReturnSettlementError(w,services.ErrInvalidReturnSettlement);return};claims,_:=auth.ClaimsFromContext(r.Context());value,err:=h.service.Create(r.Context(),claims,r.PathValue("id"),input);if err!=nil{writeReturnSettlementError(w,err);return};writeAuthJSON(w,http.StatusCreated,value)}
func(h *ReturnSettlementHandler)Void(w http.ResponseWriter,r *http.Request){var input models.ReturnSettlementVoidInput;if decodeOwnerJSON(w,r,&input)!=nil{writeReturnSettlementError(w,services.ErrInvalidReturnSettlement);return};claims,_:=auth.ClaimsFromContext(r.Context());value,err:=h.service.Void(r.Context(),claims,r.PathValue("id"),input);if err!=nil{writeReturnSettlementError(w,err);return};writeAuthJSON(w,http.StatusOK,value)}
func writeReturnSettlementError(w http.ResponseWriter,err error){switch{case errors.Is(err,repositories.ErrReturnSettlementNotFound):writeAuthJSON(w,http.StatusNotFound,map[string]string{"error":"return_settlement_not_found","message":"Return settlement not found"});case errors.Is(err,repositories.ErrReturnSettlementReturnNotFound):writeAuthJSON(w,http.StatusNotFound,map[string]string{"error":"customer_return_not_found","message":"Customer return not found"});case errors.Is(err,repositories.ErrReturnSettlementConflict):writeAuthJSON(w,http.StatusConflict,map[string]string{"error":"return_settlement_conflict","message":err.Error()});case errors.Is(err,repositories.ErrReturnSettlementVersion):writeAuthJSON(w,http.StatusConflict,map[string]string{"error":"return_settlement_version_conflict","message":err.Error()});case errors.Is(err,repositories.ErrReturnSettlementState):writeAuthJSON(w,http.StatusConflict,map[string]string{"error":"return_settlement_state_conflict","message":err.Error()});case errors.Is(err,repositories.ErrReturnSettlementOverpaid):writeAuthJSON(w,http.StatusConflict,map[string]string{"error":"return_settlement_exceeds_balance","message":err.Error()});case errors.Is(err,repositories.ErrReturnSettlementUnavailable):writeAuthJSON(w,http.StatusUnprocessableEntity,map[string]string{"error":"return_settlement_unavailable","message":err.Error()});case errors.Is(err,services.ErrBookForbidden):writeAuthJSON(w,http.StatusForbidden,map[string]string{"error":"forbidden","message":"Insufficient permissions"});case errors.Is(err,services.ErrInvalidReturnSettlement):writeAuthJSON(w,http.StatusBadRequest,map[string]string{"error":"invalid_return_settlement","message":"Invalid return settlement data"});default:writeAuthJSON(w,http.StatusInternalServerError,map[string]string{"error":"internal_error","message":"Return settlement operation failed"})}}
