package handlers

import (
	"defta-librairie/internal/auth"
	"defta-librairie/internal/models"
	"defta-librairie/internal/repositories"
	"defta-librairie/internal/services"
	"errors"
	"net/http"
	"strings"
)

type SupplierReturnHandler struct{service *services.SupplierReturnService}
type supplierReturnTransitionRequest struct{Version int `json:"version"`}
func NewSupplierReturnHandler(service *services.SupplierReturnService)*SupplierReturnHandler{return &SupplierReturnHandler{service:service}}
func(h *SupplierReturnHandler)List(w http.ResponseWriter,r *http.Request){offset,limit:=normalizeAPIPagination(r.URL.Query().Get("offset"),r.URL.Query().Get("limit"),30);claims,_:=auth.ClaimsFromContext(r.Context());values,total,err:=h.service.List(r.Context(),claims,r.URL.Query().Get("libraryId"),models.SupplierReturnFilter{Status:models.SupplierReturnStatus(r.URL.Query().Get("status")),PurchaseID:strings.TrimSpace(r.URL.Query().Get("purchaseId")),SupplierID:strings.TrimSpace(r.URL.Query().Get("supplierId")),From:strings.TrimSpace(r.URL.Query().Get("from")),To:strings.TrimSpace(r.URL.Query().Get("to"))},offset,limit);if err!=nil{writeSupplierReturnError(w,err);return};writeAuthJSON(w,http.StatusOK,map[string]interface{}{"results":values,"total":total,"offset":offset,"limit":limit})}
func(h *SupplierReturnHandler)Get(w http.ResponseWriter,r *http.Request){claims,_:=auth.ClaimsFromContext(r.Context());value,err:=h.service.Find(r.Context(),claims,r.PathValue("id"));if err!=nil{writeSupplierReturnError(w,err);return};writeAuthJSON(w,http.StatusOK,value)}
func(h *SupplierReturnHandler)Create(w http.ResponseWriter,r *http.Request){var input models.SupplierReturnInput;if decodeOwnerJSON(w,r,&input)!=nil{writeSupplierReturnError(w,services.ErrInvalidSupplierReturn);return};claims,_:=auth.ClaimsFromContext(r.Context());value,err:=h.service.Create(r.Context(),claims,input);if err!=nil{writeSupplierReturnError(w,err);return};writeAuthJSON(w,http.StatusCreated,value)}
func(h *SupplierReturnHandler)Update(w http.ResponseWriter,r *http.Request){var input models.SupplierReturnInput;if decodeOwnerJSON(w,r,&input)!=nil{writeSupplierReturnError(w,services.ErrInvalidSupplierReturn);return};claims,_:=auth.ClaimsFromContext(r.Context());value,err:=h.service.Update(r.Context(),claims,r.PathValue("id"),input);if err!=nil{writeSupplierReturnError(w,err);return};writeAuthJSON(w,http.StatusOK,value)}
func(h *SupplierReturnHandler)Cancel(w http.ResponseWriter,r *http.Request){var input supplierReturnTransitionRequest;if decodeOwnerJSON(w,r,&input)!=nil{writeSupplierReturnError(w,services.ErrInvalidSupplierReturn);return};claims,_:=auth.ClaimsFromContext(r.Context());value,err:=h.service.Cancel(r.Context(),claims,r.PathValue("id"),input.Version);if err!=nil{writeSupplierReturnError(w,err);return};writeAuthJSON(w,http.StatusOK,value)}
func writeSupplierReturnError(w http.ResponseWriter,err error){switch{case errors.Is(err,repositories.ErrSupplierReturnNotFound):writeAuthJSON(w,http.StatusNotFound,map[string]string{"error":"supplier_return_not_found","message":"Supplier return not found"});case errors.Is(err,repositories.ErrSupplierReturnConflict):writeAuthJSON(w,http.StatusConflict,map[string]string{"error":"supplier_return_version_conflict","message":err.Error()});case errors.Is(err,repositories.ErrSupplierReturnState):writeAuthJSON(w,http.StatusConflict,map[string]string{"error":"supplier_return_not_editable","message":err.Error()});case errors.Is(err,repositories.ErrSupplierReturnQuantity):writeAuthJSON(w,http.StatusConflict,map[string]string{"error":"supplier_return_quantity_exceeded","message":err.Error()});case errors.Is(err,repositories.ErrSupplierReturnPurchase):writeAuthJSON(w,http.StatusUnprocessableEntity,map[string]string{"error":"purchase_unavailable","message":err.Error()});case errors.Is(err,repositories.ErrSupplierReturnLine):writeAuthJSON(w,http.StatusBadRequest,map[string]string{"error":"invalid_purchase_line","message":err.Error()});case errors.Is(err,services.ErrBookForbidden):writeAuthJSON(w,http.StatusForbidden,map[string]string{"error":"forbidden","message":"Insufficient permissions"});case errors.Is(err,services.ErrInvalidSupplierReturn):writeAuthJSON(w,http.StatusBadRequest,map[string]string{"error":"invalid_supplier_return","message":"Invalid supplier return data"});default:writeAuthJSON(w,http.StatusInternalServerError,map[string]string{"error":"internal_error","message":"Supplier return operation failed"})}}
